# Generated by Django 2.1.1 on 2018-09-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photoLink',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='image_link',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='fb_link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='author',
            name='github_link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter_link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='link_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
