# Generated by Django 2.1.1 on 2018-09-22 12:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180922_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=10),
        ),
    ]
