# Generated by Django 2.1.1 on 2018-09-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180922_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='desc',
            field=models.CharField(default='Read more about this blog... ', max_length=200),
            preserve_default=False,
        ),
    ]
